version: '3.11.3'

services:

  Project:
    image: project:latest
    ports:
      - "8000:8000"
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    depends_on:
      - Project
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx1G  
    depends_on:
      - zookeeper

  servers: 
    image:  kafka:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  producer:
    image: kafka_producer:latest
    depends_on:
      - servers

  consumer:
    image: kafka_consumer:latest
    depends_on:
      - producer